"""Shared ISO country / Indian state code mappings for ecommerce integrations.

Used by Unicommerce today; other connectors (Shopify, Amazon, ...) can import the
same maps and helpers instead of maintaining their own copies.
"""

from __future__ import annotations

# ISO 3166-1 alpha-2 country code -> ERPNext Country name
COUNTRY_CODE_TO_NAME = {
	"AD": "Andorra",
	"AE": "United Arab Emirates",
	"AF": "Afghanistan",
	"AG": "Antigua and Barbuda",
	"AI": "Anguilla",
	"AL": "Albania",
	"AM": "Armenia",
	"AO": "Angola",
	"AQ": "Antarctica",
	"AR": "Argentina",
	"AS": "American Samoa",
	"AT": "Austria",
	"AU": "Australia",
	"AW": "Aruba",
	"AZ": "Azerbaijan",
	"BA": "Bosnia and Herzegovina",
	"BB": "Barbados",
	"BD": "Bangladesh",
	"BE": "Belgium",
	"BF": "Burkina Faso",
	"BG": "Bulgaria",
	"BH": "Bahrain",
	"BI": "Burundi",
	"BJ": "Benin",
	"BM": "Bermuda",
	"BR": "Brazil",
	"BS": "Bahamas",
	"BT": "Bhutan",
	"BV": "Bouvet Island",
	"BW": "Botswana",
	"BY": "Belarus",
	"BZ": "Belize",
	"CA": "Canada",
	"CF": "Central African Republic",
	"CH": "Switzerland",
	"CI": "Ivory Coast",
	"CK": "Cook Islands",
	"CL": "Chile",
	"CM": "Cameroon",
	"CN": "China",
	"CO": "Colombia",
	"CR": "Costa Rica",
	"CU": "Cuba",
	"CV": "Cape Verde",
	"CX": "Christmas Island",
	"CY": "Cyprus",
	"CZ": "Czech Republic",
	"DE": "Germany",
	"DJ": "Djibouti",
	"DK": "Denmark",
	"DM": "Dominica",
	"DO": "Dominican Republic",
	"DZ": "Algeria",
	"EC": "Ecuador",
	"EE": "Estonia",
	"EG": "Egypt",
	"EH": "Western Sahara",
	"ER": "Eritrea",
	"ES": "Spain",
	"ET": "Ethiopia",
	"FI": "Finland",
	"FJ": "Fiji",
	"FK": "Falkland Islands",
	"FM": "Micronesia",
	"FO": "Faroe Islands",
	"FR": "France",
	"GA": "Gabon",
	"GB": "United Kingdom",
	"GD": "Grenada",
	"GE": "Georgia",
	"GF": "French Guiana",
	"GG": "Guernsey",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GL": "Greenland",
	"GM": "Gambia",
	"GN": "Guinea",
	"GP": "Guadeloupe",
	"GQ": "Equatorial Guinea",
	"GR": "Greece",
	"GS": "South Georgia and the South Sandwich Islands",
	"GT": "Guatemala",
	"GU": "Guam",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HK": "Hong Kong",
	"HM": "Heard Island and McDonald Islands",
	"HN": "Honduras",
	"HR": "Croatia",
	"HT": "Haiti",
	"HU": "Hungary",
	"ID": "Indonesia",
	"IE": "Ireland",
	"IL": "Israel",
	"IM": "Isle of Man",
	"IN": "India",
	"IO": "British Indian Ocean Territory",
	"IQ": "Iraq",
	"IR": "Iran",
	"IS": "Iceland",
	"IT": "Italy",
	"JE": "Jersey",
	"JM": "Jamaica",
	"JO": "Jordan",
	"JP": "Japan",
	"KE": "Kenya",
	"KG": "Kyrgyzstan",
	"KH": "Cambodia",
	"KI": "Kiribati",
	"KM": "Comoros",
	"KN": "Saint Kitts and Nevis",
	"KR": "Korea, Republic of",
	"KW": "Kuwait",
	"KY": "Cayman Islands",
	"KZ": "Kazakhstan",
	"LB": "Lebanon",
	"LC": "Saint Lucia",
	"LI": "Liechtenstein",
	"LK": "Sri Lanka",
	"LR": "Liberia",
	"LS": "Lesotho",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"LV": "Latvia",
	"LY": "Libya",
	"MA": "Morocco",
	"MC": "Monaco",
	"MD": "Moldova, Republic of",
	"ME": "Montenegro",
	"MG": "Madagascar",
	"MH": "Marshall Islands",
	"MK": "Macedonia",
	"ML": "Mali",
	"MM": "Myanmar",
	"MN": "Mongolia",
	"MO": "Macao",
	"MP": "Northern Mariana Islands",
	"MQ": "Martinique",
	"MR": "Mauritania",
	"MS": "Montserrat",
	"MT": "Malta",
	"MU": "Mauritius",
	"MV": "Maldives",
	"MW": "Malawi",
	"MX": "Mexico",
	"MY": "Malaysia",
	"MZ": "Mozambique",
	"NA": "Namibia",
	"NC": "New Caledonia",
	"NE": "Niger",
	"NF": "Norfolk Island",
	"NG": "Nigeria",
	"NI": "Nicaragua",
	"NL": "Netherlands",
	"NO": "Norway",
	"NP": "Nepal",
	"NR": "Nauru",
	"NU": "Niue",
	"NZ": "New Zealand",
	"OM": "Oman",
	"PA": "Panama",
	"PE": "Peru",
	"PF": "French Polynesia",
	"PG": "Papua New Guinea",
	"PH": "Philippines",
	"PK": "Pakistan",
	"PL": "Poland",
	"PM": "Saint Pierre and Miquelon",
	"PN": "Pitcairn",
	"PR": "Puerto Rico",
	"PT": "Portugal",
	"PW": "Palau",
	"PY": "Paraguay",
	"QA": "Qatar",
	"RO": "Romania",
	"RS": "Serbia",
	"RU": "Russian Federation",
	"RW": "Rwanda",
	"SA": "Saudi Arabia",
	"SB": "Solomon Islands",
	"SC": "Seychelles",
	"SD": "Sudan",
	"SE": "Sweden",
	"SG": "Singapore",
	"SI": "Slovenia",
	"SJ": "Svalbard and Jan Mayen",
	"SK": "Slovakia",
	"SL": "Sierra Leone",
	"SM": "San Marino",
	"SN": "Senegal",
	"SO": "Somalia",
	"SR": "Suriname",
	"ST": "Sao Tome and Principe",
	"SV": "El Salvador",
	"SY": "Syria",
	"SZ": "Swaziland",
	"TC": "Turks and Caicos Islands",
	"TD": "Chad",
	"TF": "French Southern Territories",
	"TG": "Togo",
	"TH": "Thailand",
	"TJ": "Tajikistan",
	"TK": "Tokelau",
	"TM": "Turkmenistan",
	"TN": "Tunisia",
	"TO": "Tonga",
	"TR": "Turkey",
	"TT": "Trinidad and Tobago",
	"TV": "Tuvalu",
	"TW": "Taiwan",
	"TZ": "Tanzania",
	"UA": "Ukraine",
	"UG": "Uganda",
	"UM": "United States Minor Outlying Islands",
	"US": "United States",
	"UY": "Uruguay",
	"UZ": "Uzbekistan",
	"VC": "Saint Vincent and the Grenadines",
	"VE": "Venezuela, Bolivarian Republic of",
	"VN": "Vietnam",
	"VU": "Vanuatu",
	"WF": "Wallis and Futuna",
	"WS": "Samoa",
	"YE": "Yemen",
	"YT": "Mayotte",
	"ZA": "South Africa",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
}

# Indian state/UT codes (marketplaces / Uni / WooCommerce / Shopify)
# -> ERPNext / India Compliance state name.
# Includes alternate codes used by different platforms (e.g. CT/CG, OR/OD, TL/TG/TS).
INDIAN_STATE_CODE_TO_NAME = {
	"AN": "Andaman and Nicobar Islands",
	"AP": "Andhra Pradesh",
	"AD": "Andhra Pradesh",
	"AR": "Arunachal Pradesh",
	"AS": "Assam",
	"BR": "Bihar",
	"CH": "Chandigarh",
	"CT": "Chhattisgarh",
	"CG": "Chhattisgarh",
	"DN": "Dadra and Nagar Haveli and Daman and Diu",
	"DD": "Dadra and Nagar Haveli and Daman and Diu",
	"DH": "Dadra and Nagar Haveli and Daman and Diu",
	"DL": "Delhi",
	"GA": "Goa",
	"GJ": "Gujarat",
	"HR": "Haryana",
	"HP": "Himachal Pradesh",
	"JK": "Jammu and Kashmir",
	"JH": "Jharkhand",
	"JR": "Jharkhand",
	"KA": "Karnataka",
	"KL": "Kerala",
	"LA": "Ladakh",
	"LD": "Lakshadweep Islands",
	"MP": "Madhya Pradesh",
	"MH": "Maharashtra",
	"MN": "Manipur",
	"ML": "Meghalaya",
	"MZ": "Mizoram",
	"NL": "Nagaland",
	"OR": "Odisha",
	"OD": "Odisha",
	"PY": "Puducherry",
	"PB": "Punjab",
	"RJ": "Rajasthan",
	"SK": "Sikkim",
	"TN": "Tamil Nadu",
	"TL": "Telangana",
	"TG": "Telangana",
	"TS": "Telangana",
	"TR": "Tripura",
	"UP": "Uttar Pradesh",
	"UT": "Uttarakhand",
	"UL": "Uttarakhand",
	"UK": "Uttarakhand",
	"WB": "West Bengal",
}


def get_country_name(country_code: str | None, default: str | None = None) -> str | None:
	"""Return ERPNext country name for an ISO country code.

	If code is unknown, returns `default` if given, else the original code.
	"""
	if not country_code:
		return default
	if country_code in COUNTRY_CODE_TO_NAME:
		return COUNTRY_CODE_TO_NAME[country_code]
	return default if default is not None else country_code


def get_indian_state_name(state_code: str | None, default: str | None = None) -> str | None:
	"""Return ERPNext/India Compliance state name for an Indian state code.

	If code is unknown, returns `default` if given, else the original value
	(may already be a full state name).
	"""
	if not state_code:
		return default
	if state_code in INDIAN_STATE_CODE_TO_NAME:
		return INDIAN_STATE_CODE_TO_NAME[state_code]
	return default if default is not None else state_code


def map_country_and_state(
	country_code: str | None,
	state: str | None,
) -> tuple[str | None, str | None]:
	"""Map country code and (for India) state code to ERPNext address values.

	Returns (country_name, state_name).
	"""
	country_name = get_country_name(country_code)
	state_name = state
	if country_code == "IN":
		state_name = get_indian_state_name(state)
	return country_name, state_name
